# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.3
language: objective-c
podfile: Example/Podfile
cache: cocoapods
befor_install:
- gem install cocoapods 
- pod install
script:
- set -o pipefail && xcodebuild clean build test -workspace Example/FTFontLabelCategory.xcworkspace -scheme FTFontLabelCategory-Example -sdk iphonesimulator11.0 -destination 'platform=iOS Simulator,name=iPhone 6,OS=10.0' ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty
- pod lib lint
